### ISSUE TITLE
Adjust verification provider logic to new app flow

### ISSUE THREAD

**Issue by nataschaberg** [jolocom/verification-provider#3]
### Description
Due to the change of app architecture, the verification provider service needs to be adjusted.

### TODO
- [ ] Design and document user friendly flows for phone number and email address with particular attention to mobile phone use cases.
- [ ] Implement the designed flows
- [ ] Update the tests to reflect the new functionality
- [ ] Create sub issues for the appropriate bodies of work.
